/**
 * 
 */
package com.felix.math.master;

/**
 * @author agoli
 *
 */
public enum Operations {
	ADDITION, 
	SUBTRACTION, 
	MULTIPLICATION, 
	DIVISION, 
	MODULUS,
	SQUARE, 
	CUBE, 
	POWER, 
	SQUARE_ROOT, 
	CUBE_ROOT,
	N_ROOT,
	PERCENTAGE,
	PRIME,
	RECIPROCAL,
	FACTORIAL,
	YES_NO,
	MULTIPLE_ARITHMETIC,
	REMAINDER,
	FIBONACCI,	
	NUMBER_TYPE,
	
	//Princeton
	//http://introcs.cs.princeton.edu/java/92symbolic/
	
	//REFER Complex.java
	COMPLEX_NUMBER_OPS,
	COMPLEX_REAL_NO,
	COMPLEX_IMAGINARY_NO,
	COMPLEX_ADDITION,
	COMPLEX_SUBTRACTION,
	COMPLEX_MULTIPLICATION,
	COMPLEX_DIVISION,
	COMPLEX_MULTIPLE_ARITH, //(a/b)*c
	COMPLEX_CONJUGATE,
	COMPLEX_ABSOLUTE,
	COMPLEX_TANGENT,
	
	//RATIONAL Ops - Refer Rational.java
	RATIONAL,
	RATIONAL_ADDITION,
	RATIONAL_MUTLTIPLICATION,
	RATIONAL_SUBTRACTION,
	RATIONAL_DIVISION,
	
	
}
