package com.felix.math.master;

public enum NumberTypes {
	PRIME,
	COMPOSITE,
	WHOLE,
	COMPLEX,//PENDING
	INTEGER,//Pending
	REAL,
	NATURAL,
	NEGATIVE,
	POSITIVE,
	RATIONAL,
	IRRATIONAL,
	FRACTIONAL,
	DECIMAL,
	TERMINATING_DECIMAL,
	NON_TERMINATION_DECIMAL,
	IMAGINARY,
	BINARY,
	ROMAN_NUMERAL,
	NON_NEGATIVE_NUMBER,
	NON_POSITIVE_NUMBER,
	SCIENTIFIC_NOTATION,
	EVEN_NUMBER,
	ODD_NUMBER,
	SQUARE_OF_NUMBER,
	CUBE_OF_NUMBER,
	POWER_OF_NUMBER,
	
	//http://en.wikipedia.org/wiki/List_of_types_of_numbers
	//Polygonal numbers
	TRIANGULAR_NUMBER,
	SQUARE_NUMBER, 
	PENTAGONAL_NUMBER, 
	HEXAGONAL_NUMBER, 
	HEPTAGONAL_NUMBER,
	OCTAGONAL_NUMBER, 
	NONAGONAL_NUMBER, 
	DECAGONAL_NUMBER, 
	DODECAGONAL_NUMBER,
	
	//Algebraic numbers
	ALGEBRAIC_NUMBER,
	TRANSCENDENTAL_NUMBER,
	QUADRATIC_SURD,
	CONSTRUCTIBLE_NUMBER,
	ALGEBRAIC_INTEGER,
	
	//Non-standard numbers
	TRANSFINITE_NUMBERS,
	ORDINAL_NUMBERS,
	INFINITESIMALS,
	HYPERREAL_NUMBERS,
	SURREAL_NUMBERS,
	
	COMPUTABLE_NUMBER,
	DEFINABLE_NUMBER,

	

}
